### PR TITLE
Updates to Get Involved page

### PR DESCRIPTION
**Pull request by elletjies**

### CODE REVIEW

**Comment by elletjies** [comment]
@maneesha can I assume that I will only be able to update the links once the other pages are ready?

**Comment by maneesha** [comment]
@elletjies Yes, we can have placeholders for links now, and update them once everything is complete.

**Comment by maneesha** [comment]
This looks good @elletjies 
Is it ready to merge or are you still working through it?

**Comment by elletjies** [comment]
@maneesha it is ready to merge!

**Pull request merged**
